### ISSUE TITLE
[Suggestion] What the Colors mean

### ISSUE THREAD

**Issue by manmaed** [CreeperHost/MineTogether#170]
if some one types something like what are the color names for? system will reply what the color names are like it dose for the rules

**Comment by Scipio3** [comment]
White means nothing.
Purple means he is currently playing with your modpack.
Yellow means he is your friend and he has a name.
And the red means he talks to you.

**Comment by Draylynn** [comment]
Or you know, you can ask a chat moderator... Don't give the robots all the jobs... DEY TOOK ARR JABS.
I frequently post up the colour codes.
