### ISSUE TITLE
[Suggestion] Naming Filter

### ISSUE THREAD

**Issue by TemporaryForToday20200324-1** [CreeperHost/MineTogether#202]
CreeperHost,

I would like to suggest the following feature: Please consider implementing an inappropriate word list filter to the portion of MineTogether that allows a user to suggest a name to a to-be friend.

It's no secret that Minecraft targets younger audiences and that, because of this, you might find that a lot good percentage MineTogether's users are younger in age. MineTogether advertises itself as a place for all ages to come and chat about their game and other clean topics. This is what users agree to when initiating MineTogether, it's displayed in the rules in MineTogether and it's heavily enforced by those who moderate MineTogether.

A feature of MineTogether is to add a user as a friend. When you add a friend, a text field pops up and asks what username you would like to suggest (that will be displayed) to the invitee user. In cases where a suggested name is inappropriate, there is no filter to prevent that inviting user from sending it to the invitee. I've personally received friend requests from multiple users with inappropriate nicknames. For example, the inviting person could suggest the name of an adult website or racial slur as their nickname and force send or spam it via the friend request system. The filters usually in place to protect Global Chat would be powerless to stop it. That invited user receiving that spam may be even single-digit age. This also causes confusion in MineTogether Global Chat over a nickname being mentioned, it's their name but it violates the Global Chat rules, etc.

There needs to be a filter in place for nicknames. Ideally, the invited user would nickname a person on their list and not the other way around where it is force suggested. (This is similar to Steam and other platform nickname systems.)

Please consider this suggestion request. I can provide more context, if it is necessary.

**Comment by TemporaryForToday20200324-1** [comment]
Addendum:

I now see that there was some decisions made in December to update the naming portion of MineTogether. It was said that opting out of an anonymized "User####" may be coming. I just wanted to add that context provided in this post may be an unintended consequence of implementing those changes on the "opt-out side."

#146 

(Sorry if you get a low priority ping on this. I came across that post and felt it was relevant enough to link to this one while things were pending. Thanks.)

**Comment by ThePaul-T** [comment]
Honestly, somehow missed this.

The intended way for this to work was the user adding the friend got to pick how their name appeared, and this is kind of a misunderstanding when it was implemented, and we'll fix it in a minor release shortly now all the backlog is finished (at least in 1.12)

Mr @gigabit101 will sort.
