### ISSUE TITLE
corrupt mod banned me and a friend falsely. we're scared hell remove our report if we do it on creeperhost(draylynn)

### ISSUE THREAD

**Issue by gliderbanana** [CreeperHost/MineTogether#428]
yo this Draylynn guy saying he represents your company from some big position in it is making all kinds of strikes at other people in his IRC for this minetogether app and says he can ban anyone, which he proved he can by banning me and all my friends falsely for the following reasons
1. said CH "cut corners" in passing
2. he pasted his discord in chat so we contacted him and apparently that is a bannable offence on its own(not even joking look at the screenshots lmfao)
3. trying to talk with him instead of fighting like children and solve this without involving his higher ups

![image](https://user-images.githubusercontent.com/40529036/102705025-6edd2f80-4248-11eb-8403-ecba4576f071.png)

everything he said here is complete BS because he said CH cut corners in passing and like 2 people saw it....draylynn continued it for another 10 minutes when it could have been ignored and like noone would have said anything about it since they were mostly talking about other stuff
![image](https://user-images.githubusercontent.com/40529036/102705039-93d1a280-4248-11eb-8fe2-72a9199dba1e.png)

he said that he was "one of the good mods" and "just wait until <someone's name i dont know> comes online" so im gonna be revoking and trying to chargeback my CH server for this if this is fr the case and he's not reviewed at all since what he is doing is really messed up and puts a bad light on the company even for those unaffected by him and just seeing his tantrums in chat. we were really trying to be respectful for a long time taking his under the table hits and now im just putting this bluntly because he doesnt seem to be open to reason at all like a good mod should be
it wasnt just our group showing concern about this too. before we all got banned from the IRC random other players started coming to our aid, mostly after he outright said he can ban someone if he does not like them, this was at at like 9.40 for me(est)

**Comment by gliderbanana** [comment]
we have all officially chargebacked as of now due to this persons behavior and will be attempting to contact the company directly since the issues by my friends are just being closed

**Comment by gliderbanana** [comment]
alright i figured out how to actually contact creeperhost so ill go to the correct sources instead of here&unsubscribe to the thread since im guessing if there's one bad mod they have their friends in there too. apologies if this bad apples behavior doesnt represent you or if the chargebacks affect employees at all

**Comment by Draylynn** [comment]
Appeals for related bans will not be removed: The boss himself will be made aware of the incident and I can tell you, the appeals will stand.

There's two sides to every story, I noticed the important parts of chat from MineTogether aren't in here.

To summarise:
At no point was I offensive towards any of the users or made toxic comments, I was doing my job.
The ensuing behaviour from the ban only reinforces why the MineTogether chat rules are so harshly followed - How you conduct yourself online speaks absolute volumes about who you are.
...And I was entirely professional, I asked for the user to elaborate, knowing full well who I was, they ignored me and tried to laugh it off - You don't ignore the chat moderators on any platform.

The user was banned for:
Slander
Wheaton's Law
Toxic behaviour

When banned, friends were informed that I wouldn't discuss it over Discord and they were to use the appeal process as I (and to coin the very refence they made) would not "cut corners", this was ignored too.
I was then harassed on Discord with extremely offensive language in a group-cyberbullying effort, in this day an' age, absolutely deplorable behaviour.

Quite frankly, we do not want customers who behave like this, best of luck where-ever you take your service.

Not sure what you expected from this, as I told you, any appeals will be denied, the whole Discord fiasco sealed it into a permanent ban for all involved.
This issue will be closed.

**Comment by memcpy22** [comment]
Not sure what you get from this besides childish revenge since you're being toxic even in this message and try to eliminate communication to you. And yes we will make your boss aware with the steps we're taking right now, and will make sure the modding communities we are in know about this.

**Comment by Draylynn** [comment]
Oh by all means, feel free to link them to this GitHub issue listing.

**Comment by memcpy22** [comment]
Don't worry, we are. Do you have anything to say for yourself? We'll make sure to link you to the content we post when it's done.

**Comment by memcpy22** [comment]
Of course publicly where you can't claim people are "hounding" you for being abusive.

**Comment by Draylynn** [comment]
If you have nothing to contribute to the conversation, do not spam/scroll it with excess responses.

**Comment by compilres** [comment]
How sad, you still can't back up your own radical actions dude.

**Comment by compilres** [comment]
Dude you said you're so high in this company too, why do you only have 8 contributions on GitHub??? Are you serious??

**Comment by Draylynn** [comment]
8 contributions on GitHub, not all staff are programmers and no, you won't find a social media account for me either.
Your friends broke chat rules, they were banned - I have nothing to say about it anymore, I did my job, I have nothing to back up and what you're doing now, only reiterates why the rules are so harsh in the first place.

This whole fiasco after that incident does not shed a good light on your actions or behaviour, what is wrong with you?
You're literally bullying right now and by your own actions being toxic.

**Comment by KirokiFreedom** [comment]
No fiasco is happening, and noone's bullying you. We're trying to get reasoning from your radical actions and you took push to shove, so we are shoving back for your corruption. You're throwing a tantrum over a guy in a block game saying he didn't prefer your hosting service, cry about it. 
Or better yet, actually do your job and go ban the people who need it instead of the ones that just feed your ego lmfao.

**Comment by KirokiFreedom** [comment]
What kind of person claims people are bullying them because they say what they did?? How childish is it to cry wolf like that dude, you're another kind of low.
Rules arnet harsh, you just have them setup so you can ban anyone who you don't like and you know it.

**Comment by Draylynn** [comment]
The only people talking here right now, should be the 2 banned users and the staff.
