### ISSUE TITLE
Issue with specific moderator on the team

### ISSUE THREAD

**Issue by gimblo** [CreeperHost/MineTogether#436]
Moderator of this host "Draylynn" has been causing problems with me and my team.

He has repeatedly used foul language and toxic behavior when speaking to my team.  He refuses to allow us to use the services which we have been promised, and threatens removal, no refund permitted.

He removed one of our members from the service due to an illegitimate reason and refuses to undo this error.

It would be great if this could be solved quickly, and hopefully with as little argument as possible.

(If any additional evidence is needed, I would be happy to comply privately)

Thanks,
    gimblo

Image supporting claims: https://imageshare.best/image.php?id=01565H.png

**Comment by Draylynn** [comment]
I would remind anyone to avoid clicking any links from these users without scrutinising them heavily first, as virus and hacking threats have been made.
The issue of "Dray doing her job" has already been opened in another GitHub issue and is awaiting a response.

If you want to share images, use a more mainstream site, like imghur, lightshot etc.

**Comment by gimblo** [comment]
I would say this is an unprofessional way to handle the situation.  No hacking threats have been made; we are simply attempting to resolve an issue.

"Dray doing her job" is a very biased response to the situation.  I believe we will be finding other hosts for our endeavors.

Thanks,
gimblo

**Comment by Cloudhunter** [comment]
If you ask me, those who currently have childish immature friends brigading an issue tracker should not try and lecture anyone about "professionalism"
