### ISSUE TITLE
Draylynn when he encounters an innocent player:

### ISSUE THREAD

**Issue by memcpy22** [CreeperHost/MineTogether#438]
https://user-images.githubusercontent.com/76273963/102707924-c1c4e000-4264-11eb-98f9-e2dc145f4df2.mp4

**Comment by gimblo** [comment]
https://user-images.githubusercontent.com/76276011/102707968-1700f180-4265-11eb-99ec-93d835e3677c.mp4

**Comment by compilres** [comment]
https://user-images.githubusercontent.com/76274145/102707974-2a13c180-4265-11eb-8c2e-35e64d769b40.mp4

**Comment by compilres** [comment]
ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ颀ꃳ門ꃳ隀ꃳ鞀ꃳ門
chingy chingy
