### ISSUE TITLE
Bug with Appealing my Ban on Minetogether

### ISSUE THREAD

**Issue by Tandy0747** [CreeperHost/MineTogether#508]
Hi I'm a disabled individual with dispraxia and I was recently banned from the mine together chat for misspelling a word that some could construe as rude (although I didn't intend that way) typing is often difficult with my condition so sometimes mistakes are made. 
But the main issue is I can't appeal my ban no matter how many times I submit the form on the mine together website I get zero response. 

To be permanently banned for a simple typing error seems quite over the top, so if anyone could help me understand why the appeals box doesn't work or could help me out with this it'd be much appreciated.

**Comment by Draylynn** [comment]
Appeal on Minetogether.io - If your appeal is denied, you'll need to wait 14 days to try again.

Your appeal was denied:
A) You spammed the appeals somehow.
B) DCD/Dyspraxia is a neurological disorder that affects fine motor control and coordination, you know what you want to say, but it comes out skewed. EG: cupboard > cuhorb. It's known as the drunken disorder, verbally causes slurring. It is not some kind of typing-Tourette's.
C) You used a racial slur in chat, you were banned for it.

**Comment by Tandy0747** [comment]
I put this appeal up when I actually cared about this mod
I made a simple typing error, yet being permanently banned and i find it
difficult to type the letter B literally is next to the Letter N.

I'm well aware of how my own condition affects me thankyou very much I
don't need some neckbearded server moderator to tell me what i do or don't
have.
